### Get Documentation
GET http://localhost:8000/

### See all blocks
GET http://localhost:8000/blocks

### Add a block
POST http://localhost:8000/blocks

{
    "message": "Hello, Korea!!!"
}

### Get a block
GET http://localhost:8000/blocks/34bb65aac5e5eca3ff3799b31b69a330bdd9afd7a8509c98de3a6296fd961323

### Get a nonexistent block
GET http://localhost:8000/blocks/nonexistent-block