### Get Documentation
GET http://localhost:8000/

### See all blocks
GET http://localhost:8000/blocks

### Mine a block
POST http://localhost:8000/blocks

{
    "address": "todo-address"
}

### Get a block
GET http://localhost:8000/blocks/09c213bbcef93f4a4513d02b9502799efe2692fc4b7b92748c1cbc72a0780333

### Get a nonexistent block
GET http://localhost:8000/blocks/nonexistent-block

### Get transaction outputs for an address
GET http://localhost:8000/addresses/todo-address/txnouts

### Get balance for an address
GET http://localhost:8000/addresses/todo-address/balance

### Get transactions inside blockchain memory pool
GET http://localhost:8000/mempool

### Make transaction inside blockchain memory pool
POST http://localhost:8000/transactions

{
    "from": "todo-address",
    "to": "my-address",
    "amount": 35
}