[package]
name = "nomadcoin-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "nomadcoin"
path = "src/lib.rs"

[dependencies]
sha2 = "0.9.3"
rocket = "0.5.0-rc.1"
serde = "1.0.130"

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.1"
features = ["tera"]